vich_uploader:
    db_driver: orm

    mappings:
        vehicule_images:
            uri_prefix: '%vehicule_images%'
            upload_destination: '%kernel.project_dir%/public%vehicule_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
